spring:
  datasource:
    url: jdbc:mysql://localhost/account_management?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  freemarker:
    cache: false
    charset: UTF-8
    enabled: true
    suffix: .html
server:
  port: 80